### ISSUE TITLE
Car routing request

### ISSUE THREAD

**Issue by johnpercy** [develar/gh-routing-data#1]
Could you please do car routing data for Great Britain
Thanks!

**Comment by develar** [comment]
Car, right? Do you aware about https://github.com/graphhopper/graphhopper/issues/1401? Have you tried car routing for Germany — is calculation time is ok?

Or you just want car routing using CH (so, ~1 second to calculate 700 km route) without turn restrictions? Because you simply cannot wait when mentioned issue will be fixed, right?

**Comment by johnpercy** [comment]
I just wanted to see how Graphhopper compares with BRouter for car routing. I've not tried this version of GH with your routing data for Germany, though I have tried GH before using data I had generated though Cruiser.
In the light of what you're saying, it looks like it might be sensible to wait for a resolution first.

**Comment by develar** [comment]
> I just wanted to see how Graphhopper compares with BRouter for car routing

You can try https://graphhopper.com/maps/ to see if routing is better or not. Or simply use online (Locus uses it by default).

If need, I can prepare using CH.

**Comment by develar** [comment]
Car routing supported as part of regular downloads. update: reopened, not all maps have required data yet.
